### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by yumjoo** [Jianf-Wang/GBDL#3]
I'm wondering how you configure and run the dataset（KiTS-19, Atrial Segmentation Challenge） on other methods UA-MT , SASSNet, Double-UA, Tripled-UA, CoraNet . I would appreciate it if you could provide the code for the other methods you are using.

**Comment by Jianf-Wang** [comment]
Hi, many thanks for your interest to this work. We built our baselines based on their released codes by modifying their dataloaders, as we are different from those methods in terms of data preprocessing. As for Double-UA, we totally implemented it by ourselves, since the authors do not release any code.  I only reserve the codes for our method, and I cannot access to the previous lab server anymore. So, I am sorry that I cannot provide the codes for other methods, but it is not quite difficult to modify their released codes. You can also directly cite the results from our paper, when you make comparisions.

**Comment by yumjoo** [comment]
Thanks for your reply! For a more fair comparison while citing the results from your paper，could you please provide the txt file for KiTs-19 like train_AtriaSeg.txt and test_AtriaSeg.txt.

**Comment by Jianf-Wang** [comment]
Hi, those files are also in the previous lab server, so I cannot access to them.   But the training set and testing set are randomly split, and we ran 5 times for different splits. You can randomly split training and testing sets, and prepare 5 text files (simiar to train_AtriaSeg.txt and test_AtriaSeg.txt)  to perform experiments.

**Comment by yumjoo** [comment]
I see. Thank you！
